env:
  webextensions: true
  es6: true
  jest/globals: true
plugins:
  - 'jest'
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
  - 'plugin:jest/recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
globals:
  global: false
